Return-Path: <linux-wireless-owner@vger.kernel.org>
X-Original-To: lists+linux-wireless@lfdr.de
Delivered-To: lists+linux-wireless@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 93529757337
	for <lists+linux-wireless@lfdr.de>; Tue, 18 Jul 2023 07:33:11 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229583AbjGRFdJ (ORCPT <rfc822;lists+linux-wireless@lfdr.de>);
        Tue, 18 Jul 2023 01:33:09 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:38736 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229633AbjGRFdI (ORCPT
        <rfc822;linux-wireless@vger.kernel.org>);
        Tue, 18 Jul 2023 01:33:08 -0400
Received: from smtp-out2.suse.de (smtp-out2.suse.de [195.135.220.29])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 30707E55
        for <linux-wireless@vger.kernel.org>; Mon, 17 Jul 2023 22:33:05 -0700 (PDT)
Received: from imap2.suse-dmz.suse.de (imap2.suse-dmz.suse.de [192.168.254.74])
        (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
         key-exchange X25519 server-signature ECDSA (P-521) server-digest SHA512)
        (No client certificate requested)
        by smtp-out2.suse.de (Postfix) with ESMTPS id C53C21FDBE;
        Tue, 18 Jul 2023 05:33:03 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=suse.de; s=susede2_rsa;
        t=1689658383; h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=MC0Uj7wFietNdaumqkA5DAdsWqNSOezL0uCkJGEwqdA=;
        b=wEGgTK82DZqSuUumbqxCDvcYebRIiqxHtep+U8slRRYNbtr0wu8aIsKaAm8PNJRTlgXJPC
        TbTK09dRi3Y064dpDuhklhorw9ulfhHggO+hCbuaRaY+0x4BgmkHxhlwO0fXlXz78bJQYM
        OCnnCq8LEhjf54B7hSGwITXy9fVzvYc=
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=suse.de;
        s=susede2_ed25519; t=1689658383;
        h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=MC0Uj7wFietNdaumqkA5DAdsWqNSOezL0uCkJGEwqdA=;
        b=C5SX4M0P4zOhEXFhIC1ZNp8wy0/t6KP3fwiV7xvlcmxgwsBxot5LWgnY8+ZGB+p5JBltai
        gyFZAKg7JTlfg/Dg==
Received: from imap2.suse-dmz.suse.de (imap2.suse-dmz.suse.de [192.168.254.74])
        (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
         key-exchange X25519 server-signature ECDSA (P-521) server-digest SHA512)
        (No client certificate requested)
        by imap2.suse-dmz.suse.de (Postfix) with ESMTPS id 96A13134B0;
        Tue, 18 Jul 2023 05:33:03 +0000 (UTC)
Received: from dovecot-director2.suse.de ([192.168.254.65])
        by imap2.suse-dmz.suse.de with ESMTPSA
        id CCFlIw8ktmQobwAAMHmgww
        (envelope-from <tiwai@suse.de>); Tue, 18 Jul 2023 05:33:03 +0000
Date:   Tue, 18 Jul 2023 07:33:03 +0200
Message-ID: <87351lpywg.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Larry Finger <Larry.Finger@lwfinger.net>
Cc:     Takashi Iwai <tiwai@suse.de>, Ping-Ke Shih <pkshih@realtek.com>,
        linux-wireless@vger.kernel.org
Subject: Re: rtw89 driver and compressed firmware files
In-Reply-To: <f5e75b2b-14eb-7ffc-6716-70324d2d13c5@lwfinger.net>
References: <87zg3uvawm.wl-tiwai@suse.de>
        <f5e75b2b-14eb-7ffc-6716-70324d2d13c5@lwfinger.net>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) Emacs/27.2 Mule/6.0
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-Spam-Status: No, score=-2.1 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_BLOCKED,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE,URIBL_BLOCKED
        autolearn=ham autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-wireless.vger.kernel.org>
X-Mailing-List: linux-wireless@vger.kernel.org

On Mon, 17 Jul 2023 22:25:34 +0200,
Larry Finger wrote:
> 
> On 7/17/23 10:02, Takashi Iwai wrote:
> > Hi,
> > 
> > while debugging a reported rtw89 issue
> >    https://bugzilla.suse.com/show_bug.cgi?id=1212808
> > we noticed that rtw89 driver didn't load the firmware properly.
> > 
> > And, this turned out that it's because the driver uses
> > request_partial_firmware_into_buf() function with the combination of
> > compressed firmware files (that are standard on some distros like
> > openSUSE).
> > It's a known limitation of the request_partial_firmware_into_buf() API
> > function itself; it won't load compressed files, because otherwise
> > it'd have to read the full data.  That said, the use of
> > request_partial_*() should be only for very limited use cases, and
> > this doesn't look fitting well for rtw89.
> > (And, as usual, the information is missing in the documentation :-<
> > The API document should state it clearly; I'm going to submit a patch
> > to add the information.)
> > 
> > There was already a workaround for CONFIG_SECURIY_LOADPIN_ENFORCE for
> > a similar problem, but such a fallback is required in general for all
> > cases, as it seems.
> > 
> > I can cook a hackish patch for the fallback, but I wonder whether it
> > still makes sense to keep the use of that API function.  rtw89 is the
> > only driver except for bcm-vk (where the API was introduced just for
> > this driver), after all...
> 
> Takashi,
> 
> I am trying to duplicate the OPs problem in boo#1212808. I am
> currently running with an RTW8851BE, thus I must use kernel 6.5-rc2,
> or the repo at https://github.com/lwfinger/rtw89.git, which is the
> source for the Hardware entry at openSUSE. The firmware loading code
> is common for my chip and the RTW8852BE in the bugzilla entry. In my
> dmesg output, I see the following:
> 
> [  160.142412] rtw89_8851be 0000:02:00.0: Direct firmware load for
> rtw89/rtw8851b_fw.bin failed with error -2
> [  160.142418] rtw89_8851be 0000:02:00.0: failed to early request firmware: -2
> [  160.170098] rtw89_8851be 0000:02:00.0: Firmware version 0.29.41.0,
> cmd version 0, type 5
> [  160.170103] rtw89_8851be 0000:02:00.0: Firmware version 0.29.41.0,
> cmd version 0, type 3
> [  160.505451] rtw89_8851be 0000:02:00.0: chip rfe_type is 1
> [  160.551131] rtw89_8851be 0000:02:00.0 wls1: renamed from wlan0
> 
> The first attempt fails, but the second works. The firmware file in
> question is xz compressed. This result was obtained with the in-kernel
> version of the driver.

Thanks Larry, but I guess that it happens only for multi versions such
as rtw8852b that have rtw8852a_fw.bin and rtw8852a_fw-1.bin, while
yours is rtw8851b that has only one firmware version.

And, the driver might look as if still "working".  IIUC, it's only
that the new firmware version won't be used as long as the firmware
files are compressed.

You can see more details by passing firmware_class.dyndbg=+p boot
option.

> All of this was done using Tumbleweed. My next step will be to try
> Leap 15.5 and Leap 15.4. I will report those tests later.

Note that the problem of the firmware loader is likely irrelevant with
the actual issue in the bugzilla entry above; I only gave as a
reference.

It seems that the bug there was due to the error:

  rtw89_8852be 0000:02:00.0: [ERR]pci config read 719
  rtw89_8852be 0000:02:00.0: [ERR] pcie autok fail -22
  rtw89_8852be 0000:02:00.0: failed to setup chip information

Since reloading the module works, this might be related with the PCI
power state or something else.  But it's a different topic from this
thread, which is about the firmware loader problem.


Takashi
